### ISSUE TITLE
Bare line feed characters

### ISSUE THREAD

**Issue by sirowood** [EC-Nordbund/denomailer#11]
**Describe the bug**
Your message contains invalid characters (bare line feed characters) which the email servers at yahoo.com don't support.

**To Reproduce**
When sending emails to @yahoo.com with **html**, and **content** property set to 'auto'

**Expected behavior**
No errors.

**Comment by mathe42** [comment]
Will look into it. I think there is a quick fix...

**Comment by mathe42** [comment]
Coud you provide a html example. I can't reproduce the error...

**Comment by mathe42** [comment]
Close this as no reproduction was provided. Feel free to repopen or create a new issue

**Comment by mathe42** [comment]
Maybe fixed by 8e0de37964518e18aa50edb06b99547638ddc3a6
