### ISSUE TITLE
ecoding? errors with outlook, gmail

### ISSUE THREAD

**Issue by mathe42** [EC-Nordbund/denomailer#13]
![image](https://user-images.githubusercontent.com/12182390/164730316-01012421-783e-403a-bd87-0cafcbc9a165.png)

v0.16.0 made additional encoding errors it seems. Added original message content at https://gist.github.com/xCykrix/00a71d6aaf400630910ed3e0de90b17b#file-new-original-message

---

Creating my own inbox with Ethereal and sending it via Ethereal gives the expected outcome (also sent inbound to the account via my SMTP server), but if I send it to Gmail or Outlook it has encoding errors. 0.16.1 did not resolve the issue. I'll try to send it via Gmail SMTP to see if perhaps it will have a different result.

Also:
deno 1.21.0 (release, x86_64-unknown-linux-gnu)
v8 10.0.139.17
typescript 4.6.2

posted by @xCykrix in https://github.com/EC-Nordbund/denomailer/issues/12#issuecomment-1106552060_

**Comment by xCykrix** [comment]
Alright. So I dug into it a bit more and came up with basically nothing of use besides "0a" which is what wants to appear now. Ethereal renders it correctly, but even Gmail to Gmail (used my girlfriend's Gmail to receive and mine to send) has the faulty encoding. So that pretty much narrows out it being my SMTP server causing an issue.

**Comment by mathe42** [comment]
Lol I could now reproduce it.

It has to be the gmail...

gmail -> gmail creates problem
gmail -> gmx.de creates no problem
gmx.de -> gmail creates no problem

Very strange...

**Comment by mathe42** [comment]
I'm stupid. One of the errors wasn't fixed...

**Comment by mathe42** [comment]
0.16.2 should be fine now!

**Comment by mathe42** [comment]
0.16.3 should be fine now!

**Comment by xCykrix** [comment]
@mathe42 One last slight little dumb one. Gmail is working perfectly, but Outlook (Desktop&Android) has a trailing "a" at the end for some reason when using the HTML at https://gist.github.com/xCykrix/00a71d6aaf400630910ed3e0de90b17b#file-sent-html

If I beautify the HTML it works as intended, so I'm assuming it is still just one oddball in encoding.

![image](https://user-images.githubusercontent.com/12182390/164783065-53ca3e9f-0915-4c65-acd1-b136415a1106.png)

**Comment by mathe42** [comment]
Outlook has a Option to show the raw Email could you share that?

**Comment by mathe42** [comment]
useing android Outlook I could not reproduce it...

**Comment by xCykrix** [comment]
Added to the gist. https://gist.github.com/xCykrix/00a71d6aaf400630910ed3e0de90b17b#file-raw-content-mht

It is right near the end at a comment. So confused as to where it comes from.

**Comment by mathe42** [comment]
I release 1.16.4 this should not fix it. But could you try :D. Found a stupid bug (that codepath should not be used so this should not have any effect)

**Comment by xCykrix** [comment]
Unable to reproduce it now. Not sure what you changed but it worked.

**Comment by mathe42** [comment]
ok lol.

I will close this. Then the error has to be some line ending bugs or so...
