### ISSUE TITLE
Uncaught BadResource Error

### ISSUE THREAD

**Issue by timonson** [EC-Nordbund/denomailer#19]
## Describe the bug

The following error is thrown and it can't be caught:

```
error: Uncaught (in promise) BadResource: Bad resource ID
        nwritten += await this.#writer.write(p.subarray(nwritten));
                    ^
    at async write (deno:ext/net/01_net.js:33:12)
    at async BufWriter.flush (https://deno.land/std@0.130.0/io/buffer.ts:748:21)
    at async SMTPConnection.writeCmd (https://deno.land/x/denomailer@1.0.0/client/basic/connection.ts:108:5)
    at async SMTPClient.send (https://deno.land/x/denomailer@1.0.0/client/basic/client.ts:78:7)
```

OS: Arch
deno version:
- deno 1.21.1 (release, x86_64-unknown-linux-gnu)
- v8 10.0.139.17
- typescript 4.6.2
std version: 0.138.0

**Comment by mathe42** [comment]
Could you provide a reproduction and the logs when you set in the client options `debug.log` to true see https://github.com/EC-Nordbund/denomailer#options

**Comment by timonson** [comment]
I tried but I can't because it works in a minimal reproduction like expected. Strangely it only happens when I make http requests through the native API before making a http request which invokes smtp. In this case the `send` method is stalling before the error occurs. There seems to be some kind of pile-up. If I don't do the other http requests (just normal static file requests) before that, the error doesn't happen.

**Comment by mathe42** [comment]
http-requests = fetch or what?

**Comment by timonson** [comment]
Automatic browser requests, originiating from an html file

**Comment by mathe42** [comment]
Oh... so you have also a http-server running in deno...

**Comment by timonson** [comment]
Edited previous post

**Comment by mathe42** [comment]
Are you sure the connection is not closed? If you call close and then send an EMail I would expect that or a similar error.

**Comment by timonson** [comment]
Yes you are right, that's it and it is working now. I actually closed it intentionally. I must have misunderstood the code in `denomailer/client/mod.ts` because I thought that the *internal client* would reconnect automatically. Really sorry for wasting our time.
Thanks a lot!

**Comment by mathe42** [comment]
With this
```ts
import { SMTPClient } from "https://deno.land/x/denomailer@1.0.0/mod.ts";

const client = new SMTPClient({
  debug: {
    log: true,
  },
  connection: {
    hostname: "smtp.gmail.com",
    auth: {
      username: "xxx",
      password: "xxx",
    },
  },
});

await sleep(2000);

await client.close();

await client.send({
  from: "xxx",
  to: "xxx",
  subject: "TEST",
  content: "ABC",
});

function sleep(to: number) {
  return new Promise<void>((res) => setTimeout(res, to));
}
```

I get the same error so I think your connection got closed!

**Comment by mathe42** [comment]
Never mind I fould a small bug while debuging this :D
