### ISSUE TITLE
the readme example not working on last 1.3.0 and deno 1.26

### ISSUE THREAD

**Issue by jupegarnica** [EC-Nordbund/denomailer#38]
the readme example not working on last 1.3.0 and deno 1.26

**Comment by mathe42** [comment]
What error message do you get?

Could you add

```ts
debug: {
    log: true
}
```
to the SMTPClient options and share the output? (BUT REMOVE PASSWORD + USERNAME from the logs! (Note they are encoded))

**Comment by mathe42** [comment]
> note: I got the example (changed config to use my SMTP server) runnig just now...

**Comment by mathe42** [comment]
Closing this as no reproduction was provided.
