### ISSUE TITLE
TLS connection problems

### ISSUE THREAD

**Issue by louiszgn** [EC-Nordbund/denomailer#4]
Hi 👋,
I don't know if it's the right place to report this, sorry if it's misplaced.

When I try to connect, sometimes it work but most of time I receive this error :
`InvalidData: received corrupt message`

Do someone know why ? I noticed that [this test](https://github.com/EC-Nordbund/denomailer/runs/5541230487?check_suite_focus=true) was not passed, is there a link?
This is the code used :

```typescript
try {
    await client.connect({
      hostname: 'ssl0.ovh.net',
      port: 587,
      username: MAILER_ADDRESS,
      password: MAILER_PWD,
    })

    await client.send({
      from: MAILER_ADDRESS,
      to: email,
      subject: emailTemplate.subject,
      content: emailTemplate.content,
    })
  } catch (e) {
    throw new Error(e)
  } finally {
    await client.close()
  }
```

**Comment by mathe42** [comment]
Could you post the debug output (See https://github.com/EC-Nordbund/denomailer#configuring-your-client) make shure to remove password from logs!

(You can also send it to me via Mail datenschutz@ec-nordbund.de)

The non passing test is unrelated.

**Comment by louiszgn** [comment]
Yes sure

Is this what you need ?

```
┌───────┬────────────────┐
│ (idx) │ Values         │
├───────┼────────────────┤
│     0 │ "EHLO"         │
│     1 │ "ssl0.ovh.net" │
└───────┴────────────────┘
┌───────┬────────────┐
│ (idx) │ Values     │
├───────┼────────────┤
│     0 │ "STARTTLS" │
└───────┴────────────┘
┌───────┬────────────────┐
│ (idx) │ Values         │
├───────┼────────────────┤
│     0 │ "EHLO"         │
│     1 │ "ssl0.ovh.net" │
└───────┴────────────────┘
InvalidData: received corrupt message
    at async write (deno:ext/net/01_net.js:29:12)
    at async BufWriter.flush (https://deno.land/std@0.129.0/io/buffer.ts:748:21)
    at async SmtpClient.writeCmd (https://deno.land/x/denomailer@0.10.0/smtp.ts:397:5)
    at async SmtpClient.#connect (https://deno.land/x/denomailer@0.10.0/smtp.ts:337:7)
    at async SmtpClient.connect (https://deno.land/x/denomailer@0.10.0/smtp.ts:50:5)
```

**Comment by mathe42** [comment]
Thanks - I'm currently looking into it.

**Comment by mathe42** [comment]
Can you post the output of `deno --version` too?

**Comment by louiszgn** [comment]
```
> deno --version
deno 1.20.1 (release, x86_64-pc-windows-msvc)
v8 10.0.139.6
typescript 4.6.2
```

**Comment by mathe42** [comment]
I think you use the wrong port see https://docs.ovh.com/gb/en/emails/mail-configuration-windows-10/ try 465

**Comment by louiszgn** [comment]
I tried the ports from your link but I receive this error :
```
Error: invalid cmd
    at SmtpClient.assertCode (https://deno.land/x/denomailer@0.10.0/smtp.ts:365:13)
    at SmtpClient.#connect (https://deno.land/x/denomailer@0.10.0/smtp.ts:311:10)
    at async SmtpClient.connect (https://deno.land/x/denomailer@0.10.0/smtp.ts:50:5)
```

**Comment by louiszgn** [comment]
And with connectTLS and the port you give me I have this :
```
UnexpectedEof: tls handshake eof
    at async read (deno:ext/net/01_net.js:24:19)
    at async BufReader.#fill (https://deno.land/std@0.129.0/io/buffer.ts:323:18)
    at async BufReader.readSlice (https://deno.land/std@0.129.0/io/buffer.ts:609:9)
    at async BufReader.readLine (https://deno.land/std@0.129.0/io/buffer.ts:497:14)
    at async TextProtoReader.readLineSlice (https://deno.land/std@0.129.0/textproto/mod.ts:131:11)
    at async TextProtoReader.readLine (https://deno.land/std@0.129.0/textproto/mod.ts:33:15)
    at async SmtpClient.readCmd (https://deno.land/x/denomailer@0.10.0/smtp.ts:376:20)
    at async SmtpClient.#connect (https://deno.land/x/denomailer@0.10.0/smtp.ts:311:21)
    at async SmtpClient.connectTLS (https://deno.land/x/denomailer@0.10.0/smtp.ts:59:5)
```

**Comment by louiszgn** [comment]
If it helps, I just found the [OVH article](https://docs.ovh.com/gb/en/emails/gmail-configuration/) about port 587 for an SMTP server

**Comment by mathe42** [comment]
I can reproduce the error but I don't understand it. I'm not fully into STARTTLS and SMTP but I would expect it to work...

**Comment by mathe42** [comment]
I think this is not a denomailer problem:

1.:
```ts
const conn = await Deno.connectTls({
  hostname: 'ssl0.ovh.net',
  port: 25,
})

await conn.handshake()
```
Errors for ports 25, 587, 465

2.:
```ts
import {
  BufReader,
  BufWriter,
} from "https://deno.land/std@0.129.0/io/buffer.ts";
import { TextProtoReader } from "https://deno.land/std@0.129.0/textproto/mod.ts";

const conn = await Deno.connect({
  hostname: 'ssl0.ovh.net',
  port: 25,
})

const reader = new BufReader(conn);
const writer = new BufWriter(conn);
const _reader = new TextProtoReader(reader);

const encoder = new TextEncoder()

async function send(...args: string[]) {
  console.log('[S]', args.join(' '))
  const data = encoder.encode([...args].join(" ") + "\r\n");
  await writer.write(data);
  await writer.flush();
}

async function read() {
  const result = await _reader.readLine();

  if(!result) return null
  
  console.log('[R]', result)

  const cmdCode = parseInt(result.slice(0, 3).trim());
  const cmdArgs = result.slice(3).trim();
  return {
    code: cmdCode,
    args: cmdArgs,
  };
}


await read()

await send("EHLO", 'ssl0.ovh.net');

let startTLS = false;

while (true) {
  const cmd = await read();
  if (!cmd || !cmd.args.startsWith("-")) break;
  if (cmd.args == "-STARTTLS") startTLS = true;
}


await send("STARTTLS");
await read()

const tlsCon = await Deno.startTls(conn, {
  hostname: 'ssl0.ovh.net',
});

await tlsCon.handshake()
```
Errors at handshake.

Both errors at TLS handshake so this semes to be a problem of the mail provider or with deno itself.

**Comment by mathe42** [comment]
Can you confirm that you can send mails with this config with a mail client (outlook, thunderbird,...)? If yes I will have a deeper look into it... I think this is such a strange bug that it semes to be more likely connected to the mailprovider as with deno. But not 100% sure.

**Comment by louiszgn** [comment]
I can send mails with this config with [manyuanrong/deno-smtp](https://github.com/manyuanrong/deno-smtp).
I just try with thunderbird and I receive the emails

**Comment by mathe42** [comment]
Yes but that would be unencrypted so the password is send in plain text to the server! An attacker can read it and send mails without you knowing.

STARTTLS was added so also the `connect` methods the connection get upgraded to TLS when the server supports it (in the latest version you have to expilcitly set `unsecure` to `true` to enbale that.

But the server accepts STARTTLS as it send `250-STARTTLS` after the SMTP EHLO command. And after the STARTTLS is started it sends `220 2.0.0 Ready to start TLS` but the handshake fails.

Did you try sending mails with thunderbird or only receiving?

**Comment by louiszgn** [comment]
Yes I can send mail, this is the TB config (It works with SSL/TLS too) :
![image](https://user-images.githubusercontent.com/42579209/159315864-350bbc47-5bad-422a-be15-e339de1eeb51.png)

**Comment by louiszgn** [comment]
With connectTLS and port 465 I get an handshake error just like you :
```
UnexpectedEof: tls handshake eof
    at async read (deno:ext/net/01_net.js:24:19)
    at async BufReader.#fill (https://deno.land/std@0.129.0/io/buffer.ts:323:18)
    at async BufReader.readSlice (https://deno.land/std@0.129.0/io/buffer.ts:609:9)
    at async BufReader.readLine (https://deno.land/std@0.129.0/io/buffer.ts:497:14)
    at async TextProtoReader.readLineSlice (https://deno.land/std@0.129.0/textproto/mod.ts:131:11)
    at async TextProtoReader.readLine (https://deno.land/std@0.129.0/textproto/mod.ts:33:15)
    at async SmtpClient.readCmd (https://deno.land/x/denomailer@0.10.0/smtp.ts:376:20)
    at async SmtpClient.#connect (https://deno.land/x/denomailer@0.10.0/smtp.ts:311:21)
    at async SmtpClient.connectTLS (https://deno.land/x/denomailer@0.10.0/smtp.ts:59:5)
```

**Comment by mathe42** [comment]
I will have a look how deno implements tcp and create an issue there in the next day or so. I will keep this open for now.

**Comment by louiszgn** [comment]
Thank you very much!

**Comment by mathe42** [comment]
Maybe... I will try to debug it...

**Comment by mathe42** [comment]
Note this line
```
verify error:num=20:unable to get local issuer certificate
```

And the used cipher `ECDHE-RSA-AES256-SHA384` I will check if these have inpact into deno.

**Comment by mathe42** [comment]
Cipher looks good.

**Comment by louiszgn** [comment]
A certificate that looks like this one is mentionned in [this issue](https://github.com/denoland/deno/issues/10447). The error seems to come from rustls.

**Comment by louiszgn** [comment]
We can see in [this article](https://wiki.openssl.org/index.php/TLS1.3) that TLS1.3 use exclusively it's new ciphersuites but the [rustls github repo](https://github.com/rustls/rustls) show that they supposed to support TLS1.2 ...

**Comment by mathe42** [comment]
Yes they only support a "more secure" subset of TLS1.2. But the only way this will work if the mail provider changes the certificate...

**Comment by louiszgn** [comment]
So the only way to solve this problem is to ask OVH to update their certificates?

**Comment by mathe42** [comment]
Yep... Sorry about that...

**Comment by louiszgn** [comment]
You help me a lot, I could never have made it this far without your help!
I will try to contact OVH, maybe it will work 😅

**Comment by mathe42** [comment]
I learned a lot with this issue too... I will close it and add a comment in the readme about it.

**Comment by louiszgn** [comment]
**Update**
By following [theses instructions](https://docs.ovh.com/ie/en/web-paas/configuration-routes/https/) I add the `.platform` folder and the `routes.yaml` file in my OVH server with this in it :
```yaml
"https://{default}/":
    type: upstream
    upstream: "app:http"
    tls:
      min_version: TLSv1.2
  
  "https://www.{default}/":
    type: redirect
    to: "https://{default}/"
```

Now some mails are sent but for the majority I get this error:
```
TLS alert received: AlertMessagePayload {
    level: Fatal,
    description: ProtocolVersion,
}
InvalidData: received fatal alert: ProtocolVersion
```

The function uses is `client.connectTLS()` and the port is 465

**Comment by louiszgn** [comment]
```
2 mails sent on 10 tries
┌───────┬─────────┬─────────────────────────────────────────┐
│ (idx) │ success │ message                                 │
├───────┼─────────┼─────────────────────────────────────────┤
│     0 │ false   │ "received fatal alert: ProtocolVersion" │
│     1 │ false   │ "received fatal alert: ProtocolVersion" │
│     2 │ false   │ "received fatal alert: ProtocolVersion" │
│     3 │ false   │ "received fatal alert: ProtocolVersion" │
│     4 │ false   │ "received fatal alert: ProtocolVersion" │
│     5 │ false   │ "received fatal alert: ProtocolVersion" │
│     6 │ true    │ "Mail sent"                             │
│     7 │ true    │ "Mail sent"                             │
│     8 │ false   │ "received fatal alert: ProtocolVersion" │
│     9 │ false   │ "received fatal alert: ProtocolVersion" │
└───────┴─────────┴─────────────────────────────────────────┘
```

 ```
1 mails sent on 10 tries
┌───────┬─────────┬─────────────────────────────────────────┐
│ (idx) │ success │ message                                 │
├───────┼─────────┼─────────────────────────────────────────┤
│     0 │ true    │ "Mail sent"                             │
│     1 │ false   │ "received fatal alert: ProtocolVersion" │
│     2 │ false   │ "received fatal alert: ProtocolVersion" │
│     3 │ false   │ "received fatal alert: ProtocolVersion" │
│     4 │ false   │ "received fatal alert: ProtocolVersion" │
│     5 │ false   │ "received fatal alert: ProtocolVersion" │
│     6 │ false   │ "received fatal alert: ProtocolVersion" │
│     7 │ false   │ "received fatal alert: ProtocolVersion" │
│     8 │ false   │ "received fatal alert: ProtocolVersion" │
│     9 │ false   │ "received fatal alert: ProtocolVersion" │
└───────┴─────────┴─────────────────────────────────────────┘
```

**Comment by mathe42** [comment]
I have no idea why this happens... only thing I can think of is that there is a protocol missmatch wich only happens some times depending on some random values needed for the TCP handshake but no idea if thats true or how to fix it...

**Comment by mathe42** [comment]
Thinking about it....

Could you provide full logs (with the debug options) for 1 failed and 1 sucessfull try? And use the latest version 0.11.0 (released yesterday with better logging)

**Comment by louiszgn** [comment]
This is a part of the debug output :
```
220 GARM-102R004 Wednesday, March 23, 2022
┌───────┬────────────────┐
│ (idx) │ Values         │
├───────┼────────────────┤
│     0 │ "EHLO"         │
│     1 │ "ssl0.ovh.net" │
└───────┴────────────────┘
250-OVH SMTP PROXY Hello
250-SIZE 104857600
250-ENHANCEDSTATUSCODES
250-AUTH LOGIN PLAIN
250-AUTH=LOGIN PLAIN
250 8BITMIME
┌───────┬─────────┐
│ (idx) │ Values  │
├───────┼─────────┤
│     0 │ "AUTH"  │
│     1 │ "LOGIN" │
└───────┴─────────┘
...
250 2.0.0 Ok: queued as 219E428712F4B
```

Tell me if you need more

**Comment by mathe42** [comment]
OK so sometimes TLS works sometimes not. That is nothing I can do to fix it so closing it. For new problems please create a new issue.
