### ISSUE TITLE
issue getting denomailer running

### ISSUE THREAD

**Issue by mathe42** [EC-Nordbund/denomailer#40]
@Enyorose Your code looks good (also the debug-output).
Could you try it again with the `debug.encodeLB` option  set to true?

**Comment by mathe42** [comment]
Just for your information it looks like a bug / issue with your specific smtp-server.

**Comment by Enyorose** [comment]
Hello here is the document requested, we are using an individually owned company mailer that we host on site. I read that we are unable to use the Microsoft servers and the google servers so we moved it to a different one. Would you have any idea what it may be specifically blocking so I can get my IT guys to look for it?
[debug with true.txt](https://github.com/EC-Nordbund/denomailer/files/9735301/debug.with.true.txt)

**Comment by mathe42** [comment]
Just some quick info:
1. I can see the send functions runs until here https://github.com/EC-Nordbund/denomailer/blob/main/client/basic/client.ts#L321
2. The server doesn't have reacted to sending ".\r\n". 

Some ideas to test (just use `deno vendor` so you can modify the code)

at https://github.com/EC-Nordbund/denomailer/blob/main/client/basic/client.ts#L316
try adding `await this.#connection.writeCmd("\r\n");`.

If you can send me some server-credentials so I can test directly on your smtp-server it will be faster fixed.
(email: 2pi_r2@gmx.de)

**Comment by Enyorose** [comment]
So I did as you requested and added that piece into the spot you suggested, I have also attached the .debug document.

I'm talking with my smtp server tech, what kinds of settings would you look for to fix this issue?

[afteraddingsourcecode.txt](https://github.com/EC-Nordbund/denomailer/files/9737410/afteraddingsourcecode.txt)

**Comment by Enyorose** [comment]
I have theory, I have been researching with my tech guy and it looks its recieving the message and waiting for a '.' at the end to be able to send it. I found a document on the smtp command https://www.shellhacks.com/send-email-smtp-server-command-line/ and it mentions their needs to be a period on a line by its self to signify the end. Both the server and I are getting that request, I'm sure you've built that in somewhere I'm just not sure why its not running.

**Comment by mathe42** [comment]
> I'm sure you've built that in somewhere I'm just not sure why its not running.

I can see that denomailer sends this message:

```
(1) ['.
']
```

at end of your log.

So we are here https://github.com/EC-Nordbund/denomailer/blob/main/client/basic/client.ts#L315

from there on the following happens:

```ts
  try { // started in L75
   await this.#connection.writeCmd(".\r\n"); // send . to server to end data mode (the server did not end data mode)

   this.#connection.assertCode( // the server is in "DATA-MODE" so it sends nothing so this will throw
        await this.#connection.readCmd(),
        CommandCode.OK,
      );
      await this.#cleanup();
      this.#que.next();
    } catch (ex) {
      await this.#cleanup(); // as server is still in "DATA-MODE" this is an infinite loop.
      this.#que.next();
      throw ex;
    }
  }


```

**Comment by mathe42** [comment]
Try import denomailer from `https://raw.githubusercontent.com/EC-Nordbund/denomailer/fix/data-mode/mod.ts` this should give an error and logs "Error while in datamode - connection not revoverable"

**Comment by Enyorose** [comment]
So I ran that test mod, and it provided the error code. Is there any ideas on how to make it work?

**Comment by mathe42** [comment]
No more reproduction provided so closing this.
