### ISSUE TITLE
Setup server with TLS without auth parameters gives invalidData

### ISSUE THREAD

**Issue by osieltorres** [EC-Nordbund/denomailer#50]
This is possible not an issue, but more related to setup using TLS. In my case I have setup a server which supports TLS v1.2. My questions are:

1. Is it possible to setup a TLS with only `host`, `port`, `tls` configs? 

As I don't require the `auth` parameters, but every time I enable TLS, just get:
```js
error: Uncaught (in promise) InvalidData: received corrupt message
    at async Object.pull (deno:ext/web/06_streams.js:656:29)
```
and documentation just talks about TLS with `auth` parameters.

2. Is it possible that I need to request my email provider to update to TLS v1.3 and that might be the reason why I receive this error?

`note`: By setting the server with `allowUnsecure: true` works fine, also server STARTTLS is not supported.

Provide the output of `deno --version`
deno 1.26.0 (release, x86_64-unknown-linux-gnu)
v8 10.7.193.3
typescript 4.8.3
denomailer version 1.5.0

**Comment by mathe42** [comment]
Can you provide the output of

```
openssl s_client -debug -crlf -connect your-host.de:25
```
(with your host + port)

there are some certs that are not supported by deno (some not 100% secure algorithms).

See also https://github.com/EC-Nordbund/denomailer#tls-issues

**Comment by mathe42** [comment]
closing as required output was not provided
