### ISSUE TITLE
replyTo uses name instead of mail

### ISSUE THREAD

**Issue by innovatedev-john-pope** [EC-Nordbund/denomailer#61]
## Describe the bug

Using the replyTo option on the send function doesn't work as expected.

## To Reproduce

```
client.send({
   ...
   
   replyTo: 'test <test@example.com>',
})
```

Email will be sent with a ReplyTo: `test <test>`

## Expected behavior

Should have a ReplyTo: `test <test@example.com>`

## Additional context

Looks like it is using name twice instead of mail:

https://github.com/EC-Nordbund/denomailer/blob/main/client/basic/client.ts#L137

**Comment by mathe42** [comment]
released in 1.5.3
